### ISSUE TITLE
$canvas is null

### ISSUE THREAD

**Issue by rolfen** [allotrop3/four#32]
If I insert 
  `<script type="text/javascript" src="./lib/four/dist/four.js"></script>`
in the `<head>`, then the browser somehow fails to get hold of the canvas element.
Adding it at the end of the `<body>`, as in your examples, seems to solve it.
By the way, how about being able to attach to a particular passed canvas element or by ID?

**Comment by rolfen** [comment]
`let $canvas = document.querySelector('canvas');`
This is run as soon when four.js is loaded. Obviously at that point the DOM is not fully loaded. It should be inside something link `document.addEventListener('load', function(e){ /* in here! */ })`.
Normal, expected behaviour with libraries, (AFAIK) is to load itself when it is included, but not expect any DOM. If we have an explicit call to grab the canvas, then we can also pass it arguments to pick which canvas element we want to attach to.

**Comment by allotrop3** [comment]
The id seems like a better idea. I'll put this into the next release...there is a patch release coming at the end of the month.

**Comment by AurelioDeRosa** [comment]
I'd suggest that the constructor accepts the element to use as a parameter. It's more flexible.

**Comment by rolfen** [comment]
You could also just amend the Readme to specify that the script must be included at the end of <body>

**Comment by allotrop3** [comment]
I've now added a Canvas class to handle the canvas element and the gl context in v0.3. Closing.
